#! python3

#import pyperclip

sku_map = {'AP004': {'Description': 'Herbivore - 8oz Coconut Bath Partitions',
           'Item': 'BX7284',
           'Item Category': 'Components : Components : Boxes'},
 'AP009': {'Description': 'Herbivore - 4oz Body Oil RSC Case Pack',
           'Item': 'BX7266',
           'Item Category': 'Components : Components : Boxes'},
 'AP020': {'Description': 'Herbivore - Sample Shipper',
           'Item': 'BX7273',
           'Item Category': 'Components : Components : Boxes'},
 'AP021': {'Description': 'Herbivore - Wet Mask RSC Case Pack',
           'Item': 'BX7275',
           'Item Category': 'Components : Components : Boxes'},
 'B1': {'Description': 'Herbivore - Bamboo Charcoal Soap Bar (4oz) Carton (CS)',
        'Item': 'BX7216',
        'Item Category': 'Components : Components : Boxes'},
 'B10': {'Description': 'Herbivore - 1.7 oz Lapis Oil Box (CS)',
         'Item': 'BX7203',
         'Item Category': 'Components : Components : Boxes'},
 'B11': {'Description': 'Herbivore - Mini Lapis Oil Box (CS)',
         'Item': 'BX7243',
         'Item Category': 'Components : Components : Boxes'},
 'B12': {'Description': 'Herbivore - Coconut Rose Lip Conditioner (7mL) Carton '
                        '(CS)',
         'Item': 'BX7227',
         'Item Category': 'Components : Components : Boxes'},
 'B17': {'Description': 'Herbivore - Orchid Facial Oil (50mL) Carton (CS)',
         'Item': 'BX7204',
         'Item Category': 'Components : Components : Boxes'},
 'B18': {'Description': 'Herbivore - Orchid (8mL) Carton (CS)',
         'Item': 'BX7244',
         'Item Category': 'Components : Components : Boxes'},
 'B2': {'Description': 'Herbivore - 4 oz Blue Clay Soap Bar Box (CS)',
        'Item': 'BX7293',
        'Item Category': 'Components : Components : Boxes'},
 'B22': {'Description': 'Herbivore - Rose Hibiscus Hydrating Face Mist (4oz) '
                        'Carton (CS)',
         'Item': 'BX7223',
         'Item Category': 'Components : Components : Boxes'},
 'B3': {'Description': 'Herbivore -  Pink Clay Soap Bar (4oz) Carton (CS)',
        'Item': 'BX7222',
        'Item Category': 'Components : Components : Boxes'},
 'B30': {'Description': 'Herbivore - 50 mL Pink Cloud Rosewater Moisture Creme '
                        'Box (CS)',
         'Item': 'BX7224',
         'Item Category': 'Components : Components : Boxes'},
 'B30I': {'Description': 'Herbivore - 50 mL Pink Cloud Rosewater Moisture '
                         'Creme E flute (CS)',
          'Item': 'BX7254',
          'Item Category': 'Components : Components : Boxes'},
 'B31': {'Description': 'Herbivore - Jade Roller Product Carton with Insert '
                        '(CS)',
         'Item': 'BX7240',
         'Item Category': 'Components : Components : Boxes'},
 'B37': {'Description': 'Herbivore - 30mL Bottle Influte (CS)',
         'Item': 'BX7252',
         'Item Category': 'Components : Components : Boxes'},
 'B38': {'Description': 'Herbivore - Bakuchiol (30mL) Carton (CS)',
         'Item': 'BX7212',
         'Item Category': 'Components : Components : Boxes'},
 'B38BOTF': {'Description': 'Herbivore - Bakuchiol Serum (10mL) Carton (CS)',
             'Item': 'BX7206',
             'Item Category': 'Components : Components : Boxes'},
 'B38BOTFI': {'Description': 'Herbivore - 10mL Bottle Influte (CS)',
              'Item': 'BX7249',
              'Item Category': 'Components : Components : Boxes'},
 'B4': {'Description': 'Herbivore - 2.3 oz Blue Tansy Box (CS)',
        'Item': 'BX7208',
        'Item Category': 'Components : Components : Boxes'},
 'B47': {'Description': 'Herbivore - 4 oz Coconut Ultra Hydration Body Oil Box '
                        '(CS)',
         'Item': 'BX7219',
         'Item Category': 'Components : Components : Boxes'},
 'B49': {'Description': 'Herbivore - 4 oz Jasmine Green Tea Toner Box (CS)',
         'Item': 'BX7221',
         'Item Category': 'Components : Components : Boxes'},
 'B4I': {'Description': 'Herbivore - 2.3 oz Blue Tansy E Flute (CS)',
         'Item': 'BX7251',
         'Item Category': 'Components : Components : Boxes'},
 'B5': {'Description': 'Herbivore - 2.3 oz Brighten Box (CS)',
        'Item': 'BX7209',
        'Item Category': 'Components : Components : Boxes'},
 'B51': {'Description': 'Herbivore - 30 mL Emerald Hemp Box (CS)',
         'Item': 'BX7215',
         'Item Category': 'Components : Components : Boxes'},
 'B52': {'Description': 'Herbivore - 30 mL Emerald CBD Box (CS)',
         'Item': 'BX7214',
         'Item Category': 'Components : Components : Boxes'},
 'B53I': {'Description': 'Herbivore - Amethyst (200mL) Influte (CS)',
          'Item': 'BX7211',
          'Item Category': 'Components : Components : Boxes'},
 'B54': {'Description': 'Herbivore - 4oz Boston Round Influte (CS)',
         'Item': 'BX7253',
         'Item Category': 'Components : Components : Boxes'},
 'B58T': {'Description': 'Herbivore - Jewel Box Tray (CS)',
          'Item': 'BX7241',
          'Item Category': 'Components : Components : Boxes'},
 'B64': {'Description': 'Herbivore - Emerald CBD (50mL) Carton (CS)',
         'Item': 'BX7202',
         'Item Category': 'Components : Components : Boxes'},
 'B66': {'Description': 'Herbivore - Prism 12% Serum (30mL) Carton (CS)',
         'Item': 'BX7200',
         'Item Category': 'Components : Components : Boxes'},
 'B67': {'Description': 'Herbivore - 50 mL Prism Mask 20% Box (CS)',
         'Item': 'BX7226',
         'Item Category': 'Components : Components : Boxes'},
 'B67I': {'Description': 'Herbivore - 50 mL Prism Facial E Flute (CS)',
          'Item': 'BX7255',
          'Item Category': 'Components : Components : Boxes'},
 'B67IP': {'Description': 'Herbivore - 50 mL Prism Facial Treatment IPSY Box '
                          '(CS)',
           'Item': 'BX7225',
           'Item Category': 'Components : Components : Boxes'},
 'B68': {'Description': 'Herbivore - Phoenix Facial Oil (50mL) Carton (CS)',
         'Item': 'BX7205',
         'Item Category': 'Components : Components : Boxes'},
 'B69': {'Description': 'Herbivore - Mini Phoenix Oil Box (CS)',
         'Item': 'BX7245',
         'Item Category': 'Components : Components : Boxes'},
 'B70': {'Description': 'Herbivore - 200 mL Amethyst Box (CS)',
         'Item': 'BX7210',
         'Item Category': 'Components : Components : Boxes'},
 'B72': {'Description': 'Herbivore - Amethyst Roller Box (CS)',
         'Item': 'BX7233',
         'Item Category': 'Components : Components : Boxes'},
 'B73': {'Description': 'Herbivore - Lapis Roller Box (CS)',
         'Item': 'BX7242',
         'Item Category': 'Components : Components : Boxes'},
 'B74': {'Description': 'Herbivore - Emerald 50mg CBD Cleansing Soap Bar (4oz) '
                        'Carton (CS)',
         'Item': 'BX7237',
         'Item Category': 'Components : Components : Boxes'},
 'B75I': {'Description': 'Herbivore - 100 mL Pink Cloud Cleanser eflute (CS)',
          'Item': 'BX7250',
          'Item Category': 'Components : Components : Boxes'},
 'B77': {'Description': 'Herbivore - Coconut Milk Bath Soak (8oz) Carton (CS)',
         'Item': 'BX7228',
         'Item Category': 'Components : Components : Boxes'},
 'B79': {'Description': 'Herbivore - Aquarius Creme (50mL) Carton (CS)',
         'Item': 'BX7300',
         'Item Category': 'Components : Components : Boxes'},
 'B8': {'Description': 'Herbivore - 8 oz Coconut Rose Body Polish Box (CS)',
        'Item': 'BX7230',
        'Item Category': 'Components : Components : Boxes'},
 'B85': {'Description': 'Herbivore - 30 mL Cloud Jelly Box (CS)',
         'Item': 'BX7213',
         'Item Category': 'Components : Components : Boxes'},
 'B88': {'Description': 'Herbivore - Coco Rose Body Oil (4oz) Carton (CS)',
         'Item': 'BX7301',
         'Item Category': 'Components : Components : Boxes'},
 'B89': {'Description': 'Herbivore - Lapis Facial Oil (30mL) Carton (CS)',
         'Item': 'BX7302',
         'Item Category': 'Components : Components : Boxes'},
 'B89I': {'Description': 'Herbivore - 30mL Square Bottle Influte (CS)',
          'Item': 'BX7324',
          'Item Category': 'Components : Components : Boxes'},
 'B8I': {'Description': 'Herbivore - 8oz Straight Sided Jar Influte (CS)',
         'Item': 'BX7231',
         'Item Category': 'Components : Components : Boxes'},
 'B9': {'Description': 'Herbivore - Jasmine Body Oil (4oz) Carton (CS)',
        'Item': 'BX7220',
        'Item Category': 'Components : Components : Boxes'},
 'B90': {'Description': 'Herbivore - Phoenix Facial Oil (30mL) Carton (CS)',
         'Item': 'BX7303',
         'Item Category': 'Components : Components : Boxes'},
 'B99S': {'Description': 'Herbivore - Clear Sticker Dot (1in) (CS)',
          'Item': 'LB3318',
          'Item Category': 'Labels'},
 'B99S2': {'Description': 'Herbivore - Herbivore Botanicals Sticker Dot (CS)',
           'Item': 'LB3319',
           'Item Category': 'Labels'},
 'C1': {'Description': 'Simple Aloe Vera Gel',
        'Item': 'RM4617',
        'Item Category': 'Raw Material'},
 'C10': {'Description': 'Grapeseed Oil',
         'Item': 'RM4618',
         'Item Category': 'Raw Material'},
 'C11': {'Description': 'Jojoba, Colorless  (OG)',
         'Item': 'RM3609',
         'Item Category': 'Raw Material'},
 'C12': {'Description': 'Jojoba, Golden (OG)',
         'Item': 'RM4619',
         'Item Category': 'Raw Material'},
 'C13': {'Description': 'Kukui Nut Oil Organic',
         'Item': 'RM4632',
         'Item Category': 'Raw Material'},
 'C14': {'Description': 'Leucidal Complete',
         'Item': 'RM4587',
         'Item Category': 'Raw Material'},
 'C15': {'Description': 'MCT (Fractionated Coco Oil) Organic',
         'Item': 'RM4620',
         'Item Category': 'Raw Material'},
 'C16': {'Description': 'Meadowfoam Oil',
         'Item': 'RM4547',
         'Item Category': 'Raw Material'},
 'C17': {'Description': 'Simple Papaya/Pineapple Gel',
         'Item': 'RM4621',
         'Item Category': 'Raw Material'},
 'C18': {'Description': 'Rose Hydrosol',
         'Item': 'RM4622',
         'Item Category': 'Raw Material'},
 'C19': {'Description': 'Rose Hydrosol Organic',
         'Item': 'RM4535',
         'Item Category': 'Raw Material'},
 'C2': {'Description': 'Aloe Vera Liquid',
        'Item': 'RM4623',
        'Item Category': 'Raw Material'},
 'C20': {'Description': 'Rosehip Seed Oil (OG)',
         'Item': 'RM4546',
         'Item Category': 'Raw Material'},
 'C21': {'Description': 'Ashwagandha Oil',
         'Item': 'RM4578',
         'Item Category': 'Raw Material'},
 'C22': {'Description': 'Squalane Olive',
         'Item': 'RM4540',
         'Item Category': 'Raw Material'},
 'C23': {'Description': 'Willow Bark Extract (Salix Nigra)',
         'Item': 'RM4499',
         'Item Category': 'Raw Material'},
 'C24': {'Description': 'Witch Hazel OG ',
         'Item': 'RM4579',
         'Item Category': 'Raw Material'},
 'C25': {'Description': 'Vodka',
         'Item': 'RM4624',
         'Item Category': 'Raw Material'},
 'C26': {'Description': 'White Willow Bark Extract (Salix Alba)',
         'Item': 'RM4221',
         'Item Category': 'Raw Material'},
 'C27': {'Description': 'Glycerin Organic',
         'Item': 'RM4625',
         'Item Category': 'Raw Material'},
 'C28': {'Description': 'Jasmine Hydrosol',
         'Item': 'RM4580',
         'Item Category': 'Raw Material'},
 'C29': {'Description': 'Hemp Oil Organic',
         'Item': 'RM4581',
         'Item Category': 'Raw Material'},
 'C3': {'Description': 'Aloe Vera Oil',
        'Item': 'RM4633',
        'Item Category': 'Raw Material'},
 'C30': {'Description': 'CBD oil',
         'Item': 'RM4582',
         'Item Category': 'Raw Material'},
 'C31': {'Description': 'Borage Seed Oil',
         'Item': 'RM4583',
         'Item Category': 'Raw Material'},
 'C32': {'Description': 'Alcohol (Isoporopyl 70%)',
         'Item': 'RM4626',
         'Item Category': 'Raw Material'},
 'C33': {'Description': 'Shiitake Mushroom Extract Oil Orgranic',
         'Item': 'RM4584',
         'Item Category': 'Raw Material'},
 'C38': {'Description': 'Aqua/Water',
         'Item': 'RM1001',
         'Item Category': 'Raw Material'},
 'C39': {'Description': 'Olive Oil Pomace ',
         'Item': 'RM4635',
         'Item Category': 'Raw Material'},
 'C4': {'Description': 'Organic Apricot Kernal Oil',
        'Item': 'RM4627',
        'Item Category': 'Raw Material'},
 'C40': {'Description': 'Palm Kernel Oil RBD RSPO MB S1396 -C1',
         'Item': 'RM4636',
         'Item Category': 'Raw Material'},
 'C41': {'Description': 'Pureact 138 (Decyl Glucoside/Sodium Lauroyl '
                        'Lactylate)',
         'Item': 'RM4588',
         'Item Category': 'Raw Material'},
 'C42': {'Description': 'Glyceryl Stearate (Lipo GMS - 450 VEG)',
         'Item': 'RM4589',
         'Item Category': 'Raw Material'},
 'C43': {'Description': 'Spectrastat G2-N -PL340 ',
         'Item': 'RM3398',
         'Item Category': 'Raw Material'},
 'C44': {'Description': 'Lexgard GMCY MB PL340',
         'Item': 'RM3725',
         'Item Category': 'Raw Material'},
 'C45': {'Description': 'White Tea Extract GL',
         'Item': 'RM4590',
         'Item Category': 'Raw Material'},
 'C46': {'Description': 'Solusil Coconut ',
         'Item': 'RM4591',
         'Item Category': 'Raw Material'},
 'C47': {'Description': 'Alcohol (Isopropyl 99%) ',
         'Item': 'RM4634',
         'Item Category': 'Raw Material'},
 'C48': {'Description': 'ARG-CCTG',
         'Item': 'RM4485',
         'Item Category': 'Raw Material'},
 'C49': {'Description': 'MACKADERM LIA',
         'Item': 'RM4592',
         'Item Category': 'Raw Material'},
 'C5': {'Description': 'Virgin Organic Argan Nut Oil',
        'Item': 'RM4628',
        'Item Category': 'Raw Material'},
 'C50': {'Description': 'Nalidone ',
         'Item': 'RM4593',
         'Item Category': 'Raw Material'},
 'C51': {'Description': 'Symbiomuls GC MB ',
         'Item': 'RM4637',
         'Item Category': 'Raw Material'},
 'C52': {'Description': 'TeraStat N ',
         'Item': 'RM4594',
         'Item Category': 'Raw Material'},
 'C54': {'Description': 'DERMOSOFT GMCY MB',
         'Item': 'RM4638',
         'Item Category': 'Raw Material'},
 'C55': {'Description': 'AVICEL PC-591',
         'Item': 'RM4595',
         'Item Category': 'Raw Material'},
 'C56': {'Description': 'TL-Texturlux Stabil-50',
         'Item': 'RM4639',
         'Item Category': 'Raw Material'},
 'C57': {'Description': 'Organic Sesame Seed Oil, Sesamum indicum',
         'Item': 'RM4640',
         'Item Category': 'Raw Material'},
 'C6': {'Description': 'Camellia Seed Oil OG',
        'Item': 'RM4586',
        'Item Category': 'Raw Material'},
 'C7': {'Description': 'Chia Seed Oil Organic',
        'Item': 'RM4629',
        'Item Category': 'Raw Material'},
 'C8': {'Description': 'Coco Oil, Extra Virgin',
        'Item': 'RM4630',
        'Item Category': 'Raw Material'},
 'C8B': {'Description': 'Coco Oil Evtra Virgin Box',
         'Item': 'RM4631',
         'Item Category': 'Raw Material'},
 'C9': {'Description': 'CoQ10 Caprylic Capric Triglycerides (and) Ubiquinone',
        'Item': 'RM4513',
        'Item Category': 'Raw Material'},
 'CC10': {'Description': 'Herbivore - 7mL Low Profile Clear Glass Jar, 38/400 '
                         '(CS)',
          'Item': 'XC2145',
          'Item Category': 'Components : Components : Containers'},
 'CC100PCR': {'Description': 'Herbivore - 50mL (Laura Jar) Cap, 58/400, 14mm '
                             '(Height), PCR 30-50%, with 2.0mm PE Liner (CS)',
              'Item': 'XT993',
              'Item Category': 'Components : Components : Caps'},
 'CC102': {'Description': 'Herbivore - 100mL (Lotion) Cap, 24/410 (CS)',
           'Item': 'XT1917',
           'Item Category': 'Components : Components : Caps'},
 'CC108L': {'Description': 'Herbivore - 30mL (Square) Bottle, 18/415, Screened '
                           '- Lapis (CS)',
            'Item': 'XC2126',
            'Item Category': 'Components : Components : Containers'},
 'CC109': {'Description': 'Herbivore - 30mL (Square) Dropper, 18/415, 59mm '
                          '(CS)',
           'Item': 'XT992',
           'Item Category': 'Components : Components : Caps'},
 'CC11': {'Description': 'Herbivore - 2oz Straight Sided Jar, 53/400(CS)',
          'Item': 'XC2119',
          'Item Category': 'Components : Components : Containers'},
 'CC12': {'Description': 'Herbivore - 2.3 oz Thick Wall Clear Glass Jar 58/400 '
                         '(CS)',
          'Item': 'XC2120',
          'Item Category': 'Components : Components : Containers'},
 'CC13U': {'Description': 'Herbivore - 50 mL Laura Clear Glass Jar UPG 58/400 '
                          '(CS)',
           'Item': 'XC2138',
           'Item Category': 'Components : Components : Containers'},
 'CC14': {'Description': 'Herbivore - 8 oz Paragon Clear Flint Glass Jar '
                         '58/400 (CS)',
          'Item': 'XC2153',
          'Item Category': 'Components : Components : Containers'},
 'CC15A': {'Description': 'Herbivore - 8oz Straight Sided Clear Flint Glass '
                          'Jar, 70/400 (CS)',
           'Item': 'XC2154',
           'Item Category': 'Components : Components : Containers'},
 'CC16': {'Description': 'Herbivore - 16oz Straight Sided Clear Flint Glass '
                         'Jar, 89/400 (CS)',
          'Item': 'XC2117',
          'Item Category': 'Components : Components : Containers'},
 'CC18': {'Description': 'Herbivore - 50mL (Square Bottle) Dropper, 18/415, '
                         'ERF (CS)',
          'Item': 'XT1924',
          'Item Category': 'Components : Components : Caps'},
 'CC20': {'Description': 'Herbivore - 2oz Spray Top, 20/410, 3.5" (CS)',
          'Item': 'XT1945',
          'Item Category': 'Components : Components : Caps'},
 'CC21': {'Description': 'Herbivore - 4oz Spray Top, 24/410, 4.25" (CS)',
          'Item': 'XT1947',
          'Item Category': 'Components : Components : Caps'},
 'CC22': {'Description': 'Herbivore - 8oz Spray Top, 24/410, 5.375" (CS)',
          'Item': 'XT1948',
          'Item Category': 'Components : Components : Caps'},
 'CC23': {'Description': 'Herbivore - 2oz Pump Top, 20/410, 3.5" (CS)',
          'Item': 'XT1932',
          'Item Category': 'Components : Components : Caps'},
 'CC24': {'Description': 'Herbivore - 4oz Pump Top, 24/410, 4.25" (CS)',
          'Item': 'XT1935',
          'Item Category': 'Components : Components : Caps'},
 'CC26': {'Description': 'Herbivore - White Polypropylene Dry Mask Cap 53/400 '
                         '(CS)',
          'Item': 'XT1918',
          'Item Category': 'Components : Components : Caps'},
 'CC27': {'Description': 'Herbivore - 4oz/Wet Mask/Salt Cap, 58/400, F-217, PP '
                         '(CS)',
          'Item': 'XT1919',
          'Item Category': 'Components : Components : Caps'},
 'CC27PCR': {'Description': 'Herbivore - 4oz/Wet Mask/Salt Cap, 58/400, F-217, '
                            'PP, PCR Smooth Liner, OBERK (CS)',
             'Item': 'XT1913',
             'Item Category': 'Components : Components : Caps'},
 'CC28': {'Description': 'Herbivore - 8oz (Soak/Polish) Cap [Only Fits SKS '
                         'Glass], 70/400, F217 - PP {SKS} (CS)',
          'Item': 'XT1902',
          'Item Category': 'Components : Components : Caps'},
 'CC28PCR': {'Description': 'Herbivore - \t8oz (Soak/Polish) Cap, 70/400, '
                            '12mm, F217 - PP, PCR Smooth Liner (CS)',
             'Item': 'XT1903',
             'Item Category': 'Components : Components : Caps'},
 'CC30': {'Description': 'Herbivore - 16oz Smooth White F-217 Cap 89/400 (CS)',
          'Item': 'XT1908',
          'Item Category': 'Components : Components : Caps'},
 'CC30PCR': {'Description': 'Herbivore - 16oz (Soak) Cap, 89/400, F217, PP, '
                            'PCR (CS)',
             'Item': 'XT1909',
             'Item Category': 'Components : Components : Caps'},
 'CC31': {'Description': 'Herbivore - 200mL [Amethyst] Penelope Thick Bottom '
                         'Clear Glass Jar, 89/400 (CS)',
          'Item': 'XC2121',
          'Item Category': 'Components : Components : Containers'},
 'CC32': {'Description': 'Herbivore - \t200mL (Amethyst) Cap, 89/400, ABS, '
                         'Coverpla (CS)',
          'Item': 'XT1910',
          'Item Category': 'Components : Components : Caps'},
 'CC34U': {'Description': 'Herbivore - 50mL (Laura Jar) Cap, 58/400, 16mm '
                          '(Height), ABS  (CS)',
           'Item': 'XT1905',
           'Item Category': 'Components : Components : Caps'},
 'CC36': {'Description': 'Herbivore - 7.5mL Clear Glass Jar, 33/400 (CS)',
          'Item': 'XC2146',
          'Item Category': 'Components : Components : Containers'},
 'CC38': {'Description': 'Herbivore - 15mL Clear Glass Jar, 40/400 (CS)',
          'Item': 'XC2112',
          'Item Category': 'Components : Components : Containers'},
 'CC4': {'Description': 'Herbivore - 8mL (Square, Not Screened) Clear Glass '
                        'Bottle, 13/415 (CS)',
         'Item': 'XC2147',
         'Item Category': 'Components : Components : Containers'},
 'CC40': {'Description': 'Herbivore - 30mL (Plat Lisse) Cap, 51/400, Urea (CS)',
          'Item': 'XT1912',
          'Item Category': 'Components : Components : Caps'},
 'CC43': {'Description': 'Herbivore - 30mL (Laura Jar) Cap, 48/400, Urea (CS)',
          'Item': 'XT1911',
          'Item Category': 'Components : Components : Caps'},
 'CC4SE': {'Description': 'Herbivore - 8mL (Square) Bottle, 13/415, Screened - '
                          'Emerald (CS)',
           'Item': 'XC2148',
           'Item Category': 'Components : Components : Containers'},
 'CC4SL': {'Description': 'Herbivore - 8mL (Square) Bottle, 13/415, Screened - '
                          'Lapis (CS)',
           'Item': 'XC2149',
           'Item Category': 'Components : Components : Containers'},
 'CC4SO': {'Description': 'Herbivore - 8mL (Square) Bottle, 13/415, Screened - '
                          'Orchid (CS)',
           'Item': 'XC2150',
           'Item Category': 'Components : Components : Containers'},
 'CC4SP': {'Description': 'Herbivore - 8mL (Square) Bottle, 13/415, Screened - '
                          'Phoenix (CS)',
           'Item': 'XC2151',
           'Item Category': 'Components : Components : Containers'},
 'CC5': {'Description': 'Herbivore - 1 oz Boston Round Clear Glass Bottle '
                        '20/400 (CS)',
         'Item': 'XC2105',
         'Item Category': 'Components : Components : Containers'},
 'CC55': {'Description': 'Herbivore - 8oz (Soak/Polish) Cap [Only Fits Piramal '
                         'Glass], 70/400, 12mm (Height), Urea {Coverpla} (CS)',
          'Item': 'XT1901',
          'Item Category': 'Components : Components : Caps'},
 'CC56PR': {'Description': 'Herbivore - 30mL (Holographic Deco for Prism 12%) '
                           'Bottle, 20/400, UPG (CS)',
            'Item': 'XC2124',
            'Item Category': 'Components : Components : Containers'},
 'CC56U': {'Description': 'Herbivore - 30 mL Cylindrical Clear Glass Bottle '
                          '20/400 (CS)',
           'Item': 'XC2123',
           'Item Category': 'Components : Components : Containers'},
 'CC58': {'Description': 'Herbivore - 11.8 mL Moore Flint Bottle Clear Glass '
                         'Bottle 13/415 (CS)',
          'Item': 'XC2111',
          'Item Category': 'Components : Components : Containers'},
 'CC59': {'Description': 'Herbivore - 4 oz Straight Sided Clear Glass Jar '
                         '58/400 (CS)',
          'Item': 'XC2131',
          'Item Category': 'Components : Components : Containers'},
 'CC6': {'Description': 'Herbivore - 50 mL Square Bottle Clear Glass Bottle '
                        '18/415 (CS)',
         'Item': 'XC2141',
         'Item Category': 'Components : Components : Containers'},
 'CC61': {'Description': 'Herbivore - 8 mL White Smooth Dropper 13/415 (CS)',
          'Item': 'XT1928',
          'Item Category': 'Components : Components : Caps'},
 'CC62': {'Description': 'Herbivore - 15 mL Round Clear Glass Bottle 20/410 '
                         '(CS)',
          'Item': 'XC2114',
          'Item Category': 'Components : Components : Containers'},
 'CC63': {'Description': 'Herbivore - 15 mL Square Clear Glass Bottle 18/415 '
                         '(CS)',
          'Item': 'XC2115',
          'Item Category': 'Components : Components : Containers'},
 'CC64': {'Description': 'Herbivore - 0.5oz Boston Round Clear Glass Bottle, '
                         '18/400 (CS)',
          'Item': 'XC2107',
          'Item Category': 'Components : Components : Containers'},
 'CC64TP': {'Description': 'Herbivore - 0.5oz Spray Top, 18/415, 2.5" (CS)',
            'Item': 'XT1944',
            'Item Category': 'Components : Components : Caps'},
 'CC65': {'Description': 'Herbivore - 3" White Cut (1 oz), Spray Top 20/400 '
                         '(CS)',
          'Item': 'XT1946',
          'Item Category': 'Components : Components : Caps'},
 'CC67': {'Description': 'Herbivore - 11.8mL [10mL] Dropper, 13/415, 45mm, ERF '
                         '(CS)',
          'Item': 'XT1921',
          'Item Category': 'Components : Components : Caps'},
 'CC68': {'Description': 'Herbivore - 15mL (Round) Dropper, 20/410, 58mm, ERF '
                         '(CS)',
          'Item': 'XT1925',
          'Item Category': 'Components : Components : Caps'},
 'CC6SL': {'Description': 'Herbivore - 50mL (Square) Bottle, 18/415, Screened '
                          '- Lapis (CS)',
           'Item': 'XC2142',
           'Item Category': 'Components : Components : Containers'},
 'CC6SO': {'Description': 'Herbivore - 50mL (Square) Bottle, 18/415, Screened '
                          '- Orchid (CS)',
           'Item': 'XC2143',
           'Item Category': 'Components : Components : Containers'},
 'CC7': {'Description': 'Herbivore - 2oz Boston Round Clear Glass Bottle, '
                        '20/400 (CS)',
         'Item': 'XC2118',
         'Item Category': 'Components : Components : Containers'},
 'CC70': {'Description': 'Herbivore - 30mL Dropper, 20/410, 60mm, ERF (CS)',
          'Item': 'XT1927',
          'Item Category': 'Components : Components : Caps'},
 'CC72': {'Description': 'Herbivore - White Screened ABS Cap 38/400 (CS)',
          'Item': 'XT1920',
          'Item Category': 'Components : Components : Caps'},
 'CC73': {'Description': 'Herbivore - 7.5mL (F-217) Cap, 33/400, PP (CS)',
          'Item': 'XT1915',
          'Item Category': 'Components : Components : Caps'},
 'CC74': {'Description': 'Herbivore - 15mL Cap, 40/440, ABS (CS)',
          'Item': 'XT1904',
          'Item Category': 'Components : Components : Caps'},
 'CC77': {'Description': 'Herbivore - 58/400 Sealing Disc [50mL Laura Jar], '
                         'ERF (CS)',
          'Item': 'XT1943',
          'Item Category': 'Components : Components : Caps'},
 'CC77PCR': {'Description': 'Herbivore - 58/400 Sealing Disk [50mL Laura Jar] '
                            '{ERF} (Thicker PCR) (CS)',
             'Item': 'XT991',
             'Item Category': 'Components : Components : Caps'},
 'CC79': {'Description': 'Herbivore - 70/400 Sealing Disc (with Tab) [8oz '
                         'Jar], 70mm, PETG (CS)',
          'Item': 'XT1939',
          'Item Category': 'Components : Components : Caps'},
 'CC79E': {'Description': 'Herbivore - 60.4 mm Sealing Disk 70/400 (CS)',
           'Item': 'XT1938',
           'Item Category': 'Components : Components : Caps'},
 'CC80': {'Description': 'Herbivore - Tri Sealing Disc [200mL Amethyst], 89mm '
                         '(CS)',
          'Item': 'XT1940',
          'Item Category': 'Components : Components : Caps'},
 'CC86': {'Description': 'Herbivore - 15mL (Square) Dropper, 18/415, 59.5mm, '
                         'ERF (CS)',
          'Item': 'XT1926',
          'Item Category': 'Components : Components : Caps'},
 'CC88': {'Description': 'Herbivore - 50mL (Prism 20%) Cap, 60/400, ABS (CS)',
          'Item': 'XT1914',
          'Item Category': 'Components : Components : Caps'},
 'CC89': {'Description': 'Herbivore - 50mL (Holographic Deco for Prism 20%) '
                         'Jar, 60/400 (CS)',
          'Item': 'XC2140',
          'Item Category': 'Components : Components : Containers'},
 'CC8A': {'Description': 'Herbivore - 4oz Boston Round Clear Glass Bottle, '
                         '24/400 (CS)',
          'Item': 'XC2130',
          'Item Category': 'Components : Components : Containers'},
 'CC9': {'Description': 'Herbivore - 8oz Boston Round Clear Flint Glass, '
                        '24/400 (CS)',
         'Item': 'XC2152',
         'Item Category': 'Components : Components : Containers'},
 'CC90': {'Description': 'Herbivore -60/400 Sealing Disk [50mL Prism 20%] (CS)',
          'Item': 'XT1942',
          'Item Category': 'Components : Components : Caps'},
 'CC91': {'Description': 'Herbivore - 3.3mL [5mL] Clear Glass Bottle, 13/415 '
                         '(CS)',
          'Item': 'XC2132',
          'Item Category': 'Components : Components : Containers'},
 'CC92': {'Description': 'Herbivore - 100mL Bottle White Treatment (Lotion) '
                         'Pump, 88mm, 24/400 (CS)',
          'Item': 'XT1931',
          'Item Category': 'Components : Components : Caps'},
 'CC93': {'Description': 'Herbivore - 50mL Bottle White Treatment (Lotion) '
                         'Pump, 41mm, 24/400 (CS)',
          'Item': 'XT1933',
          'Item Category': 'Components : Components : Caps'},
 'CC94': {'Description': 'Herbivore - 50 mL Cleanser Glass Bottle 24/410 (CS)',
          'Item': 'XC2135',
          'Item Category': 'Components : Components : Containers'},
 'CC96': {'Description': 'Herbivore - 2oz Heavenly Mist Spray Top, 20/410 (CS)',
          'Item': 'XT1950',
          'Item Category': 'Components : Components : Caps'},
 'CC97': {'Description': 'Herbivore - 4oz Heavenly Mist Spray Top, 24/410 (CS)',
          'Item': 'XT1951',
          'Item Category': 'Components : Components : Caps'},
 'CC98': {'Description': 'Herbivore - 3.3mL [5mL] Dropper, 13/415, 39.5mm, ERF '
                         '(CS)',
          'Item': 'XT1923',
          'Item Category': 'Components : Components : Caps'},
 'CP0124': {'Description': 'Herbivore - 1oz Bottle Case Pack (10/bundle) (CS)',
            'Item': 'BX7311',
            'Item Category': 'Components : Components : Boxes'},
 'CP0224': {'Description': 'Herbivore - 2oz Bottle Case Pack '
                           '[9-1/2x6-5/16x4-7/8] (CS)',
            'Item': 'BX7315',
            'Item Category': 'Components : Components : Boxes'},
 'CP0570': {'Description': 'Herbivore - 5mL Round Bottle Case '
                           'Pack[10-11/16x7-1/2x2-1/2] (25/bundle) (CS)',
            'Item': 'BX7317',
            'Item Category': 'Components : Components : Boxes'},
 'CP0824': {'Description': 'Herbivore - 8oz Bottle Case Pack (15/bundle) (CS)',
            'Item': 'BX7319',
            'Item Category': 'Components : Components : Boxes'},
 'CP0850': {'Description': 'Herbivore - 8mL Face Oil Case Pack '
                           '[12x6-1/8x3-1/2] (25/bundle) (CS)',
            'Item': 'BX7318',
            'Item Category': 'Components : Components : Boxes'},
 'CP1048': {'Description': 'Herbivore - 10mL Round Bottle Case Pack (CS)',
            'Item': 'BX7304',
            'Item Category': 'Components : Components : Boxes'},
 'CP1612': {'Description': 'Herbivore - 16oz Soak Case Pack(15/bundle) (CS)',
            'Item': 'BX7309',
            'Item Category': 'Components : Components : Boxes'},
 'CP3054': {'Description': 'Herbivore - 18 x 12 x 4 Case Pack',
            'Item': 'BX7298',
            'Item Category': 'Components : Components : Boxes'},
 'CP5024': {'Description': 'Herbivore - 50mL Facial Oil Case Pack '
                           '[9-7/8x6-5/8x4-3/4] (15/bundle) (CS)',
            'Item': 'BX7316',
            'Item Category': 'Components : Components : Boxes'},
 'CPAY12': {'Description': 'Herbivore - 16 x 12 1/4 x 3 3/4 Case Pack',
            'Item': 'BX7297',
            'Item Category': 'Components : Components : Boxes'},
 'CPFR48': {'Description': 'Herbivore - Facial Roller Case Pack (25/bundle) '
                           '(CS)',
            'Item': 'BX7322',
            'Item Category': 'Components : Components : Boxes'},
 'CPGS50': {'Description': 'Herbivore - 16x6x6 [Gua Sha Box] White Indestructo '
                           'Web Mailer (100/bundle) (CS)',
            'Item': 'BX7335',
            'Item Category': 'Components : Components : Boxes'},
 'CPPM24': {'Description': 'Herbivore - Prism 20 Case Pack '
                           '[12x9x4-1/4](25/bundle) (CS)',
            'Item': 'BX7323',
            'Item Category': 'Components : Components : Boxes'},
 'CPSK24': {'Description': 'Herbivore - 8oz Soak/Polish Case Pack (25/bundle) '
                           '(CS)',
            'Item': 'BX7320',
            'Item Category': 'Components : Components : Boxes'},
 'CPST24': {'Description': 'Herbivore - 8oz Soaking Salts Case Pack (CS)',
            'Item': 'BX7321',
            'Item Category': 'Components : Components : Boxes'},
 'D1': {'Description': 'Blue Clay, Cambrian',
        'Item': 'RM4641',
        'Item Category': 'Raw Material'},
 'D10': {'Description': 'Rosehip Powder',
         'Item': 'RM4642',
         'Item Category': 'Raw Material'},
 'D11': {'Description': 'Tourmaline Powder (U)',
         'Item': 'RM4643',
         'Item Category': 'Raw Material'},
 'D12': {'Description': 'Ceara Sea Salt, Coarse (Pure Ocean)',
         'Item': 'RM4596',
         'Item Category': 'Raw Material'},
 'D13': {'Description': 'Himalayan Pink Salt',
         'Item': 'RM4597',
         'Item Category': 'Raw Material'},
 'D14': {'Description': 'Sonoma Pacific Sea Salt Fine (U)',
         'Item': 'RM4644',
         'Item Category': 'Raw Material'},
 'D15': {'Description': 'Bio-mulsion wax (OLIVEM 1000)',
         'Item': 'RM3724',
         'Item Category': 'Raw Material'},
 'D16': {'Description': 'Candelilla Wax (U)',
         'Item': 'RM4645',
         'Item Category': 'Raw Material'},
 'D17': {'Description': 'EcoSoya 210 (U)',
         'Item': 'RM4646',
         'Item Category': 'Raw Material'},
 'D18': {'Description': 'Organic Shea Butter',
         'Item': 'RM4647',
         'Item Category': 'Raw Material'},
 'D19': {'Description': 'Sodium Bicarbonate (Baking Soda)',
         'Item': 'RM4648',
         'Item Category': 'Raw Material'},
 'D2': {'Description': 'Kaolin Clay, White',
        'Item': 'RM4649',
        'Item Category': 'Raw Material'},
 'D20': {'Description': 'Fine Granulated Sugar',
         'Item': 'RM4650',
         'Item Category': 'Raw Material'},
 'D21': {'Description': 'Epsom Salt Ex Fine (Magnesium Sulfate USP)',
         'Item': 'RM4651',
         'Item Category': 'Raw Material'},
 'D22': {'Description': 'Amethyst Powder',
         'Item': 'RM4598',
         'Item Category': 'Raw Material'},
 'D23': {'Description': 'Hyaluronic Acid LMW .8-1.0 Dal',
         'Item': 'RM4533',
         'Item Category': 'Raw Material'},
 'D24': {'Description': 'Potassium Sorbate (U)',
         'Item': 'RM4652',
         'Item Category': 'Raw Material'},
 'D25': {'Description': 'French Green Clay',
         'Item': 'RM4653',
         'Item Category': 'Raw Material'},
 'D26': {'Description': 'Fito Cambrian Blue Clay ',
         'Item': 'RM4659',
         'Item Category': 'Raw Material'},
 'D27': {'Description': 'Charcoal ',
         'Item': 'RM4660',
         'Item Category': 'Raw Material'},
 'D27S': {'Description': 'Smol Charcoals ',
          'Item': 'RM4661',
          'Item Category': 'Raw Material'},
 'D28': {'Description': 'Hyaluronic Acid ULMW >6000 ',
         'Item': 'RM4601',
         'Item Category': 'Raw Material'},
 'D29': {'Description': 'Sodium Hydroxide ',
         'Item': 'RM4662',
         'Item Category': 'Raw Material'},
 'D3': {'Description': 'Pink Clay, French',
        'Item': 'RM4654',
        'Item Category': 'Raw Material'},
 'D30': {'Description': 'Citric Acid USP/FCC',
         'Item': 'RM4663',
         'Item Category': 'Raw Material'},
 'D31': {'Description': 'Aloe Vera Gel 200x ',
         'Item': 'RM4666',
         'Item Category': 'Raw Material'},
 'D32': {'Description': 'Hyaluronic Acid 1.5-1.7DA (05-ACT-SOHY)',
         'Item': 'RM4664',
         'Item Category': 'Raw Material'},
 'D33': {'Description': 'Xanthan Gum (Keltrol CG Sft-V)',
         'Item': 'RM4665',
         'Item Category': 'Raw Material'},
 'D34': {'Description': 'L-Arginine Powder',
         'Item': 'RM4667',
         'Item Category': 'Raw Material'},
 'D3J': {'Description': 'Jarxotic Pink Clay ',
         'Item': 'RM3855',
         'Item Category': 'Raw Material'},
 'D4': {'Description': 'Rose Clay',
        'Item': 'RM4537',
        'Item Category': 'Raw Material'},
 'D5': {'Description': 'German Chamomile Powder',
        'Item': 'RM4655',
        'Item Category': 'Raw Material'},
 'D6': {'Description': 'Coconut Milk Powder Vegan*',
        'Item': 'RM4599',
        'Item Category': 'Raw Material'},
 'D7': {'Description': 'Coconut Water Powder (U)*',
        'Item': 'RM4600',
        'Item Category': 'Raw Material'},
 'D8': {'Description': 'Rice Powder (U)',
        'Item': 'RM4656',
        'Item Category': 'Raw Material'},
 'D9A': {'Description': 'Rose Petal Powder',
         'Item': 'RM4657',
         'Item Category': 'Raw Material'},
 'D9B': {'Description': 'Rose Petal Powder Drum',
         'Item': 'RM4658',
         'Item Category': 'Raw Material'},
 'DL1': {'Description': 'Herbivore - 2 oz After Sun Mist Double Label (CS)',
         'Item': 'LB350012',
         'Item Category': 'Labels'},
 'DL10': {'Description': 'Herbivore - 16 oz Coconut Milk Bath Soak Double '
                         'Label (CS)',
          'Item': 'LB3305',
          'Item Category': 'Labels'},
 'DL11': {'Description': 'Herbivore - 8 oz Detox Salts Double Label (CS)',
          'Item': 'LB350016',
          'Item Category': 'Labels'},
 'DL13': {'Description': 'Herbivore - 2 oz Jasmine Oil Double Label (CS)',
          'Item': 'LB3113',
          'Item Category': 'Labels'},
 'DL15': {'Description': 'Herbivore - 2 oz Lavender Sea Mist Double Label (CS)',
          'Item': 'LB3114',
          'Item Category': 'Labels'},
 'DL16': {'Description': 'Herbivore - 8 oz Lavender Sea Mist Double Label (CS)',
          'Item': 'LB3127',
          'Item Category': 'Labels'},
 'DL17': {'Description': 'Herbivore - 4 oz Post Shave Double Label (CS)',
          'Item': 'LB3119',
          'Item Category': 'Labels'},
 'DL2': {'Description': 'Herbivore - 8 oz After Sun Mist Double Label (CS)',
         'Item': 'LB3309',
         'Item Category': 'Labels'},
 'DL21': {'Description': 'Herbivore - 15 mL Birghten Double Label (CS)',
          'Item': 'LB3303',
          'Item Category': 'Labels'},
 'DL23': {'Description': 'Herbivore - 2 oz Jasmine Green Teat Toner Double '
                         'Label (CS)',
          'Item': 'LB3112',
          'Item Category': 'Labels'},
 'DL29': {'Description': 'Herbivore - 1 oz Rose Toner Double Label (CS)',
          'Item': 'LB3102',
          'Item Category': 'Labels'},
 'DL30': {'Description': 'Herbivore - 2 oz Rose Toner Double Label (CS)',
          'Item': 'LB3116',
          'Item Category': 'Labels'},
 'DL31': {'Description': 'Herbivore - 4 oz Rose Toner Double Label (CS)',
          'Item': 'LB350014',
          'Item Category': 'Labels'},
 'DL32': {'Description': 'Herbivore - 4 oz Coconut Bath Soak [Double Label] '
                         'Label (CS)',
          'Item': 'LB3118',
          'Item Category': 'Labels'},
 'DL36': {'Description': 'Herbivore - 15 mL Blue Tansy Double Label (CS)',
          'Item': 'LB3304',
          'Item Category': 'Labels'},
 'DL37': {'Description': 'Herbivore - Calm Salts (4oz) [Double Label] Labels '
                         '(CS)',
          'Item': 'LB3414',
          'Item Category': 'Labels'},
 'DL38': {'Description': 'Herbivore - Bakuchiol [Double Label] (30mL) (CS)',
          'Item': 'LB3413',
          'Item Category': 'Labels'},
 'DL39B': {'Description': 'Herbivore - 10 mL Bakuchiol BOTF Double Label (CS)',
           'Item': 'LB350011',
           'Item Category': 'Labels'},
 'DL44': {'Description': 'Herbivore - 100 mL Pink Cloud Cleanser Double Label '
                         '(CS)',
          'Item': 'LB3302',
          'Item Category': 'Labels'},
 'DL5': {'Description': 'Herbivore - 8 oz Calm Salts Label (CS)',
         'Item': 'LB3123',
         'Item Category': 'Labels'},
 'DL51': {'Description': 'Herbivore - Prism 20% Mask [Double Label] (50mL) '
                         '(CS)',
          'Item': 'LB5178',
          'Item Category': 'Labels'},
 'DL52': {'Description': 'Herbivore - 30 mL Cloud Jelly Double Label (CS)',
          'Item': 'LB350013',
          'Item Category': 'Labels'},
 'DL54': {'Description': 'Herbivore - Coco Rose Body Polish [Double Label] '
                         '(8oz) (CS)',
          'Item': 'LB3417',
          'Item Category': 'Labels'},
 'DL55': {'Description': 'Herbivore - Emerald OG [Double Label] (30mL) (CS)',
          'Item': 'LB3418',
          'Item Category': 'Labels'},
 'DL56': {'Description': 'Herbivore - Coco Rose Body Oil [Double Label] (2oz) '
                         '(CS)',
          'Item': 'LB3415',
          'Item Category': 'Labels'},
 'DL57': {'Description': 'Herbivore - Coco Rose Body Oil [Double Label] (4oz) '
                         '(CS)',
          'Item': 'LB3416',
          'Item Category': 'Labels'},
 'DL7': {'Description': 'Herbivore - 2 oz Coconut Sea Mist Double Label (CS)',
         'Item': 'LB3111',
         'Item Category': 'Labels'},
 'DL8': {'Description': 'Herbivore - 8 oz Coconut Sea Mist Fouble Label (CS)',
         'Item': 'LB3125',
         'Item Category': 'Labels'},
 'DL9': {'Description': 'Herbivore - 8 oz Coconut Milk Bath Soak Label (CS)',
         'Item': 'LB350015',
         'Item Category': 'Labels'},
 'E09': {'Description': 'Hibiscus Extract',
         'Item': 'RM4608',
         'Item Category': 'Raw Material'},
 'E1': {'Description': 'Apricot Fragrance Oil',
        'Item': 'RM4681',
        'Item Category': 'Raw Material'},
 'E10': {'Description': 'Ginger Root Extract PF',
         'Item': 'RM4609',
         'Item Category': 'Raw Material'},
 'E11': {'Description': 'Jasmine Absolute Sambac 10%',
         'Item': 'RM4682',
         'Item Category': 'Raw Material'},
 'E12': {'Description': 'Jasmine Absolute India 10%',
         'Item': 'RM4683',
         'Item Category': 'Raw Material'},
 'E13': {'Description': 'Jasmine Sambac Absolute',
         'Item': 'RM4545',
         'Item Category': 'Raw Material'},
 'E14': {'Description': 'Lavender (Dean) Essential Oil',
         'Item': 'RM4684',
         'Item Category': 'Raw Material'},
 'E15': {'Description': 'Lime Essential Oil',
         'Item': 'RM4685',
         'Item Category': 'Raw Material'},
 'E16': {'Description': 'Neroli Egypt, OG  Essential Oil',
         'Item': 'RM4549',
         'Item Category': 'Raw Material'},
 'E17': {'Description': 'Orchid Oil',
         'Item': 'RM4686',
         'Item Category': 'Raw Material'},
 'E18': {'Description': 'Orchid Extract',
         'Item': 'RM4687',
         'Item Category': 'Raw Material'},
 'E19': {'Description': 'Cannabis Essential Oil',
         'Item': 'RM4688',
         'Item Category': 'Raw Material'},
 'E2': {'Description': 'Bergamot FCF (OG IP)',
        'Item': 'RM4610',
        'Item Category': 'Raw Material'},
 'E20': {'Description': 'Palo Santo Essential Oil',
         'Item': 'RM4689',
         'Item Category': 'Raw Material'},
 'E21': {'Description': 'Peach Flavor Oil',
         'Item': 'RM4690',
         'Item Category': 'Raw Material'},
 'E22': {'Description': 'Peppermint 2nd Essential Oil',
         'Item': 'RM4691',
         'Item Category': 'Raw Material'},
 'E23': {'Description': 'Pineapple Fragrance Oil',
         'Item': 'RM4692',
         'Item Category': 'Raw Material'},
 'E24': {'Description': 'Rose Absolute Morocco',
         'Item': 'RM4538',
         'Item Category': 'Raw Material'},
 'E25': {'Description': 'Sea Buckthorn',
         'Item': 'RM4548',
         'Item Category': 'Raw Material'},
 'E26': {'Description': 'Spearmint Essential Oil',
         'Item': 'RM4693',
         'Item Category': 'Raw Material'},
 'E27Z': {'Description': 'Tansy, Blue Essential Oil (zen)',
          'Item': 'RM4611',
          'Item Category': 'Raw Material'},
 'E28M': {'Description': 'Vanilla, Natural',
          'Item': 'RM4694',
          'Item Category': 'Raw Material'},
 'E28P': {'Description': 'Vanilla Phytoscents',
          'Item': 'RM4695',
          'Item Category': 'Raw Material'},
 'E29': {'Description': 'Vetiver (OG, Haiti) Essential Oil',
         'Item': 'RM4696',
         'Item Category': 'Raw Material'},
 'E3': {'Description': 'Cedarwood Essential Oil',
        'Item': 'RM4697',
        'Item Category': 'Raw Material'},
 'E30': {'Description': 'Vitamin E',
         'Item': 'RM4543',
         'Item Category': 'Raw Material'},
 'E31': {'Description': 'Organic Ylang Ylang Fine Essential Oil',
         'Item': 'RM4698',
         'Item Category': 'Raw Material'},
 'E32': {'Description': 'Helichrysum Essential Oil',
         'Item': 'RM4612',
         'Item Category': 'Raw Material'},
 'E33': {'Description': 'Campo Siddha Neer Pazchai Green Dye (WS)',
         'Item': 'RM3826',
         'Item Category': 'Raw Material'},
 'E34': {'Description': 'Campo Siddha Roja Sikkappu (BioColor Rose) Dye (WS)',
         'Item': 'RM4613',
         'Item Category': 'Raw Material'},
 'E35': {'Description': 'Campo Siddha Neer Kaddal Neelam Blue Dye (WS)',
         'Item': 'RM3907',
         'Item Category': 'Raw Material'},
 'E36': {'Description': 'Campo Siddha Neer Katthari Violet Dye (WS)',
         'Item': 'RM4552',
         'Item Category': 'Raw Material'},
 'E37': {'Description': 'Green Tea Extract PF',
         'Item': 'RM3492',
         'Item Category': 'Raw Material'},
 'E38': {'Description': 'Campo Siddha Indra Neelam Yenai Blue Dye (OS)',
         'Item': 'RM3825',
         'Item Category': 'Raw Material'},
 'E39': {'Description': 'Red Iron Oxide Dye / lip-liquid- Pigment Red- Castor '
                        'oil Iron Oxide',
         'Item': 'RM4668',
         'Item Category': 'Raw Material'},
 'E4': {'Description': 'Clary Sage Essential Oil',
        'Item': 'RM4669',
        'Item Category': 'Raw Material'},
 'E40': {'Description': 'White Iron Oxide Dye',
         'Item': 'RM4670',
         'Item Category': 'Raw Material'},
 'E41': {'Description': 'Yellow Iron Oxide Dye',
         'Item': 'RM4671',
         'Item Category': 'Raw Material'},
 'E42': {'Description': 'Mauve Dye',
         'Item': 'RM4672',
         'Item Category': 'Raw Material'},
 'E43': {'Description': 'Amethyst Extract',
         'Item': 'RM4673',
         'Item Category': 'Raw Material'},
 'E44': {'Description': 'Apple Extract',
         'Item': 'RM4674',
         'Item Category': 'Raw Material'},
 'E45': {'Description': 'Aspen Bark Extract Powder',
         'Item': 'RM3578',
         'Item Category': 'Raw Material'},
 'E46': {'Description': 'Bakuchiol Extract / Bakuchi Extract (kingvish)',
         'Item': 'RM4602',
         'Item Category': 'Raw Material'},
 'E47': {'Description': 'Bilberry Extract G',
         'Item': 'RM4550',
         'Item Category': 'Raw Material'},
 'E48': {'Description': 'Phyto-biotics Blueberry Stem Cell',
         'Item': 'RM4603',
         'Item Category': 'Raw Material'},
 'E49': {'Description': 'ACB Fruit Mix Enzyme',
         'Item': 'RM3912',
         'Item Category': 'Raw Material'},
 'E5': {'Description': 'Coconut Frangrance',
        'Item': 'RM4675',
        'Item Category': 'Raw Material'},
 'E50': {'Description': 'Glucono Delta Lactone',
         'Item': 'RM4604',
         'Item Category': 'Raw Material'},
 'E51': {'Description': 'Kakadu Extract PF',
         'Item': 'RM4536',
         'Item Category': 'Raw Material'},
 'E52': {'Description': 'Papaya Enzyme PF ',
         'Item': 'RM4676',
         'Item Category': 'Raw Material'},
 'E53': {'Description': 'Pineapple Enzyme PF',
         'Item': 'RM3512',
         'Item Category': 'Raw Material'},
 'E54': {'Description': 'Sodium Phytate',
         'Item': 'RM4677',
         'Item Category': 'Raw Material'},
 'E55': {'Description': 'Tremella Fuciformis Sporocarp (Mushroom) Extract ',
         'Item': 'RM4605',
         'Item Category': 'Raw Material'},
 'E56': {'Description': 'Snowflake Sparkle Mica',
         'Item': 'RM4678',
         'Item Category': 'Raw Material'},
 'E57': {'Description': 'Campo Siddha Vepuvillai Karushalai Yenai Red Dye (OS)',
         'Item': 'RM3822',
         'Item Category': 'Raw Material'},
 'E58': {'Description': 'Oat Avenanthramde',
         'Item': 'RM4679',
         'Item Category': 'Raw Material'},
 'E59': {'Description': 'Papaya Leaf Extract',
         'Item': 'RM4699',
         'Item Category': 'Raw Material'},
 'E5P': {'Description': 'Coconut Phytoscents aka SuperScents Coconut',
         'Item': 'RM4606',
         'Item Category': 'Raw Material'},
 'E6': {'Description': 'Coco Pulp CO2 (OG) Select Extract',
        'Item': 'RM4497',
        'Item Category': 'Raw Material'},
 'E60': {'Description': 'Bergamot (SOAP) Essential Oil',
         'Item': 'RM4700',
         'Item Category': 'Raw Material'},
 'E61': {'Description': 'Geranium Rose (SOAP) Essential Oil',
         'Item': 'RM4701',
         'Item Category': 'Raw Material'},
 'E62': {'Description': 'Lavender 4240 (SOAP)  Essential Oil',
         'Item': 'RM4702',
         'Item Category': 'Raw Material'},
 'E63': {'Description': 'Litsea Cubeba Essential Oil',
         'Item': 'RM4703',
         'Item Category': 'Raw Material'},
 'E64': {'Description': 'Orange 10x Essential Oil',
         'Item': 'RM4704',
         'Item Category': 'Raw Material'},
 'E65': {'Description': 'Tea Tree Essential Oil ',
         'Item': 'RM4705',
         'Item Category': 'Raw Material'},
 'E66': {'Description': 'Pink Grapefruit Cold Pressed Essential Oil',
         'Item': 'RM4706',
         'Item Category': 'Raw Material'},
 'E67': {'Description': 'Pineapple SuperScents',
         'Item': 'RM4707',
         'Item Category': 'Raw Material'},
 'E68': {'Description': 'ABS Peach Extract PF',
         'Item': 'RM4614',
         'Item Category': 'Raw Material'},
 'E69': {'Description': 'ABS Strawberry Extract G PF',
         'Item': 'RM4615',
         'Item Category': 'Raw Material'},
 'E7': {'Description': 'Eucalyptus Essential Oil',
        'Item': 'RM4607',
        'Item Category': 'Raw Material'},
 'E70': {'Description': 'FSS VEGETABLE COLLAGEN PF',
         'Item': 'RM4616',
         'Item Category': 'Raw Material'},
 'E71': {'Description': 'Bakuchiol (syntheon 4 r&d only)',
         'Item': 'RM4708',
         'Item Category': 'Raw Material'},
 'E72': {'Description': 'Strawberry Superscent ',
         'Item': 'RM4709',
         'Item Category': 'Raw Material'},
 'E73': {'Description': 'Yellow Campo Siddha Manjal Yenai, Oil Soluble Dye',
         'Item': 'RM3823',
         'Item Category': 'Raw Material'},
 'E8': {'Description': 'Geranium, Rose Essential Oil',
        'Item': 'RM4680',
        'Item Category': 'Raw Material'},
 'INCI001': {'Description': 'Herbivore - Orchid (50mL) INCI Sticker (CS)',
             'Item': 'LB3317',
             'Item Category': 'Labels'},
 'INCI003': {'Description': 'Herbivore - Lapis (50mL) INCI Sticker (CS)',
             'Item': 'LB3139',
             'Item Category': 'Labels'},
 'INCI013': {'Description': 'Herbivore - Jasmine Body Oil (4oz) INCI Sticker '
                            '(CS)',
             'Item': 'LB3315',
             'Item Category': 'Labels'},
 'INCI014': {'Description': 'Herbivore - Citrine (4oz) INCI Sticker (CS)',
             'Item': 'LB3131',
             'Item Category': 'Labels'},
 'INCI028': {'Description': 'Herbivore - Blue Clay Soap INCI Sticker (CS)',
             'Item': 'LB3313',
             'Item Category': 'Labels'},
 'INCI052': {'Description': 'Herbivore - Jasmine Green Tea Toner (4oz) INCI '
                            'Sticker (CS)',
             'Item': 'LB3136',
             'Item Category': 'Labels'},
 'INCI063': {'Description': 'Herbivore - Rose Mist [2.0] (Hydrate + Glow) INCI '
                            'Sticker (CS)',
             'Item': 'LB3144',
             'Item Category': 'Labels'},
 'INCI073': {'Description': 'Herbivore - Mini True Blue Kit INCI Sticker (CS)',
             'Item': 'LB3140',
             'Item Category': 'Labels'},
 'INCI085': {'Description': 'Herbivore - Jewel Box (Bakuchiol) INCI Sticker '
                            '(CS)',
             'Item': 'LB3316',
             'Item Category': 'Labels'},
 'INCI090': {'Description': 'Herbivore - Rose Mist [2.0] (4oz) INCI Sticker '
                            '(CS)',
             'Item': 'LB3143',
             'Item Category': 'Labels'},
 'INCI097': {'Description': 'Herbivore - Amethyst Ritual Kit INCI Sticker (CS)',
             'Item': 'LB3312',
             'Item Category': 'Labels'},
 'INCI113-1': {'Description': 'Herbivore - Cloud 9 Coco Rose INCI Sticker (CS)',
               'Item': 'LB3314',
               'Item Category': 'Labels'},
 'INCI113-2': {'Description': 'Herbivore - Cloud 9 Prism 12% INCI Sticker (CS)',
               'Item': 'LB3133',
               'Item Category': 'Labels'},
 'INCI119': {'Description': 'Herbivore - Cloud Jelly Serum (30mL) INCI Sticker '
                            '(CS)',
             'Item': 'LB5175',
             'Item Category': 'Labels'},
 'INCI119-D': {'Description': 'Herbivore - Cloud Jelly Serum (5mL) INCI '
                              'Sticker (CS)',
               'Item': 'LB3411',
               'Item Category': 'Labels'},
 'INCI120': {'Description': 'Herbivore - Bakuchiol (30mL) INCI Sticker (CS)',
             'Item': 'LB3129',
             'Item Category': 'Labels'},
 'NWPB003': {'Description': 'Herbivore - 4oz Toner Case Pack [13x8-7/8x5-7/8], '
                            '24PK RSC, NWP',
             'Item': 'BX7267',
             'Item Category': 'Components : Components : Boxes'},
 'P0124': {'Description': 'Herbivore - 1oz Bottle Partitions (30/bundle) (CS)',
           'Item': 'BX7327',
           'Item Category': 'Components : Components : Boxes'},
 'P0224': {'Description': 'Herbivore - 2oz Bottle Partitions (CS)',
           'Item': 'BX7329',
           'Item Category': 'Components : Components : Boxes'},
 'P0424': {'Description': 'Herbivore - 4oz Body Oil Partitions (CS)',
           'Item': 'BX7330',
           'Item Category': 'Components : Components : Boxes'},
 'P0570': {'Description': 'Herbivore - 5mL Partition [10-5/8x7-7/16x2] (CS)',
           'Item': 'BX7332',
           'Item Category': 'Components : Components : Boxes'},
 'P0824': {'Description': 'Herbivore - 8oz Sea Mist Partitions, Allpack '
                          '(30/bundle) (CS)',
           'Item': 'BX7333',
           'Item Category': 'Components : Components : Boxes'},
 'P1048': {'Description': 'Herbivore - 10mL Partition (CS)',
           'Item': 'BX7325',
           'Item Category': 'Components : Components : Boxes'},
 'P1612': {'Description': 'Herbivore - 16oz Coconut Bath Soak Partitions '
                          '(40/Bundle), Allpack (CS)',
           'Item': 'BX7326',
           'Item Category': 'Components : Components : Boxes'},
 'P2324': {'Description': 'Herbivore - 2.3oz Wet Mask Partition (CS)',
           'Item': 'BX7328',
           'Item Category': 'Components : Components : Boxes'},
 'P5024': {'Description': 'Herbivore - 50mL Facial Oil Partition '
                          '[9-3/4x6-1/2x4-5/8] (30/Bundle) (CS)',
           'Item': 'BX7331',
           'Item Category': 'Components : Components : Boxes'},
 'PST24': {'Description': 'Herbivore - 8oz Soaking Salt Partitions (30/bundle) '
                          '(CS)',
           'Item': 'BX7334',
           'Item Category': 'Components : Components : Boxes'},
 'RPS': {'Description': 'Herbivore - Responsible Person Sticker (CS)',
         'Item': 'LB3320',
         'Item Category': 'Labels'},
 'S-13297': {'Description': 'Herbivore - 13x13x6 Corrugated Boxes, Uline '
                            '(25/bundle) (CS)',
             'Item': 'BX7308',
             'Item Category': 'Components : Components : Boxes'},
 'S-14228': {'Description': 'Herbivore - 12x12x6 Corrugated Boxes, Uline '
                            '(15/bundle) (CS)',
             'Item': 'BX7307',
             'Item Category': 'Components : Components : Boxes'},
 'S-16756': {'Description': 'Herbivore - 24x17x12 Corrugated Boxes, Uline '
                            '(15/bundle) (CS)',
             'Item': 'BX7314',
             'Item Category': 'Components : Components : Boxes'},
 'S-4542': {'Description': 'Herbivore - 20x14x6 Corrugated Box (25/bundle) '
                           '(CS)',
            'Item': 'BX7313',
            'Item Category': 'Components : Components : Boxes'},
 'S-4754': {'Description': 'Herbivore - 12.5x12.5x6 Corrugated Box, Uline '
                           '(25/bundle) (CS)',
            'Item': 'BX7305',
            'Item Category': 'Components : Components : Boxes'},
 'S-4856': {'Description': 'Herbivore - 16x16x3 Corrugated Box, Uline '
                           '(25/bundle) (CS)',
            'Item': 'BX7310',
            'Item Category': 'Components : Components : Boxes'},
 'S-4859': {'Description': 'Herbivore - Boxes, Corrugated 18x12x4',
            'Item': 'BX7296',
            'Item Category': 'Components : Components : Boxes'},
 'SB1728': {'Description': 'Herbivore - 12x12x12 Corrugated Box, RSC '
                           '(15/bundle) (CS)',
            'Item': 'BX7306',
            'Item Category': 'Components : Components : Boxes'},
 'SB2592': {'Description': 'Herbivore - 18x12x12 Corrugated Box, RSC '
                           '(15/bundle) (CS)',
            'Item': 'BX7336',
            'Item Category': 'Components : Components : Boxes'},
 'SB3360': {'Description': 'Herbivore - 20x14x12 Corrugated Box (15/bundle) '
                           '(CS)',
            'Item': 'BX7312',
            'Item Category': 'Components : Components : Boxes'},
 'SL10': {'Description': 'Herbivore - 2.3oz Blue Tansy Label (CS)',
          'Item': 'LB3177',
          'Item Category': 'Labels'},
 'SL11': {'Description': 'Herbivore - 2.3oz Brighten Label (CS)',
          'Item': 'LB3332',
          'Item Category': 'Labels'},
 'SL12B': {'Description': 'Herbivore - 8oz Soak/Polish Bottom Label (CS)',
           'Item': 'LB3348',
           'Item Category': 'Labels'},
 'SL17': {'Description': 'Herbivore - 1.7oz Phoenix Diamond Label (CS)',
          'Item': 'LB3322',
          'Item Category': 'Labels'},
 'SL19': {'Description': 'Herbivore - 4oz Citrine Oil Label (CS)',
          'Item': 'LB3339',
          'Item Category': 'Labels'},
 'SL20': {'Description': 'Herbivore - 4 oz Jasmine Oil Label (CS)',
          'Item': 'LB3193',
          'Item Category': 'Labels'},
 'SL23': {'Description': 'Herbivore - 50 mL Pink Cloud Rosewater Moisture '
                         'Creme Label (CS)',
          'Item': 'LB3203',
          'Item Category': 'Labels'},
 'SL25': {'Description': 'Herbivore - 4 oz Jasmine Green Tea Toner Label (CS)',
          'Item': 'LB3192',
          'Item Category': 'Labels'},
 'SL26': {'Description': 'Herbivore - 4 oz Coconut Body Oil Label (CS)',
          'Item': 'LB3189',
          'Item Category': 'Labels'},
 'SL29': {'Description': 'Herbivore - 15 mL Prism 12% Label (CS)',
          'Item': 'LB350023',
          'Item Category': 'Labels'},
 'SL29D': {'Description': 'Herbivore - Prism 12% Serum [Double Label] (15mL) '
                          '{FR} (CS)',
           'Item': 'LB3420',
           'Item Category': 'Labels'},
 'SL31': {'Description': 'Herbivore - 30 mL Emerald Hemp Label (CS)',
          'Item': 'LB3335',
          'Item Category': 'Labels'},
 'SL32': {'Description': 'Herbivore - 10 mL Emerald Hemp Label (CS)',
          'Item': 'LB3159',
          'Item Category': 'Labels'},
 'SL33': {'Description': 'Herbivore - 30 mL Emerald CBD Label (CS)',
          'Item': 'LB3181',
          'Item Category': 'Labels'},
 'SL33PROP': {'Description': 'Herbivore - 30 mL Prop 65 Label (CS)',
              'Item': 'LB3142',
              'Item Category': 'Labels'},
 'SL34': {'Description': 'Herbivore - 10 mL Emerald CBD Label (CS)',
          'Item': 'LB3158',
          'Item Category': 'Labels'},
 'SL38': {'Description': 'Herbivore - 30 mL Bakuchiol Label (CS)',
          'Item': 'LB3334',
          'Item Category': 'Labels'},
 'SL39': {'Description': 'Herbivore - 10 mL Bakuchiol Label (CS)',
          'Item': 'LB350018',
          'Item Category': 'Labels'},
 'SL40': {'Description': 'Herbivore - 4 oz Coconut Rose Body Polish Label (CS)',
          'Item': 'LB3191',
          'Item Category': 'Labels'},
 'SL41': {'Description': 'Herbivore - 4oz Coconut Bath Soak Label (CS)',
          'Item': 'LB3195',
          'Item Category': 'Labels'},
 'SL43': {'Description': 'Herbivore - 200ml Amethyst Body Polish Label (CS)',
          'Item': 'LB3333',
          'Item Category': 'Labels'},
 'SL47': {'Description': 'Herbivore - 10 mL Prism 12% Label (CS)',
          'Item': 'LB3160',
          'Item Category': 'Labels'},
 'SL47CAC': {'Description': 'Herbivore - Prism 12% Serum [Double Label] (10mL) '
                            '{FR} - Cult Advent Calendar (CS)',
             'Item': 'LB5150',
             'Item Category': 'Labels'},
 'SL49': {'Description': 'Herbivore - 15 mL Emerald CBD Label (CS)',
          'Item': 'LB350020',
          'Item Category': 'Labels'},
 'SL50': {'Description': 'Herbivore - 4 oz Amethyst Body Polish Label (CS)',
          'Item': 'LB3338',
          'Item Category': 'Labels'},
 'SL51': {'Description': 'Herbivore - 15 mL Lapis Label (CS)',
          'Item': 'LB350021',
          'Item Category': 'Labels'},
 'SL52': {'Description': 'Herbivore - 15 mL Bakuchiol Label (CS)',
          'Item': 'LB3163',
          'Item Category': 'Labels'},
 'SL54': {'Description': 'Herbivore - 30 mL Prism Serum Label (CS)',
          'Item': 'LB3184',
          'Item Category': 'Labels'},
 'SL54B': {'Description': 'Herbivore - 30 mL Prism Serum Bottom Label (CS)',
           'Item': 'LB3336',
           'Item Category': 'Labels'},
 'SL55': {'Description': 'Herbivore - 50 mL Prism Treatment Facial Label (CS)',
          'Item': 'LB3344',
          'Item Category': 'Labels'},
 'SL55B': {'Description': 'Herbivore - 50 mL Prism Treatment Facial Bottom '
                          'Label (CS)',
           'Item': 'LB3204',
           'Item Category': 'Labels'},
 'SL56': {'Description': 'Herbivore - 15 mL Prism Facial Label (CS)',
          'Item': 'LB3330',
          'Item Category': 'Labels'},
 'SL56HOL': {'Description': 'Herbivore - Prism 20% Mask [Double Label] (30mL) '
                            '{FR} (CS)',
             'Item': 'LB5177',
             'Item Category': 'Labels'},
 'SL59': {'Description': 'Herbivore - 1.7 oz Emerald CBD Label (CS)',
          'Item': 'LB3153',
          'Item Category': 'Labels'},
 'SL60': {'Description': 'Herbivore - 5 mL Bakuchiol Label (CS)',
          'Item': 'LB3341',
          'Item Category': 'Labels'},
 'SL61': {'Description': 'Herbivore - 5 mL Emerald CBD Label (CS)',
          'Item': 'LB3198',
          'Item Category': 'Labels'},
 'SL63': {'Description': 'Herbivore - 5 mL Prism Serum Label (CS)',
          'Item': 'LB3200',
          'Item Category': 'Labels'},
 'SL64': {'Description': 'Herbivore - 7.5 mL Prism Treatment Label (CS)',
          'Item': 'LB3207',
          'Item Category': 'Labels'},
 'SL65B': {'Description': 'Herbivore - 100 mL Pink Cloud Cleanser Bottom Label '
                          '(CS)',
           'Item': 'LB3161',
           'Item Category': 'Labels'},
 'SL66': {'Description': 'Herbivore - 50 mL Pink Cloud Cleanser Label (CS)',
          'Item': 'LB3343',
          'Item Category': 'Labels'},
 'SL67': {'Description': 'Herbivore - 15 mL Pink Cloud Cleanser Label (CS)',
          'Item': 'LB350022',
          'Item Category': 'Labels'},
 'SL68': {'Description': 'Herbivore - 1/2 oz Rose Toner Label (CS)',
          'Item': 'LB350017',
          'Item Category': 'Labels'},
 'SL70': {'Description': 'Herbivore - 8 oz Coconut Milk Body Polish Label (CS)',
          'Item': 'LB350027',
          'Item Category': 'Labels'},
 'SL76B': {'Description': 'Herbivore - 16 oz Coconut Bath Soak Barcode Label '
                          '(CS)',
           'Item': 'LB3169',
           'Item Category': 'Labels'},
 'SL78B': {'Description': 'Herbivore - 50mL/1.7oz (Large) Bottom Label (E.g., '
                          'Aquarius) (CS)',
           'Item': 'LB3412',
           'Item Category': 'Labels'},
 'SL81': {'Description': 'Herbivore - Lip Product Stickers (CS)',
          'Item': 'LB3349',
          'Item Category': 'Labels'},
 'SL84': {'Description': 'Herbivore - 5 mL Cloud Jelly Label (CS)',
          'Item': 'LB350025',
          'Item Category': 'Labels'},
 'SL9B': {'Description': 'Herbivore - 1 oz Beard Tonic Bottom Label (CS)',
          'Item': 'LB3148',
          'Item Category': 'Labels'},
 'UPC004': {'Description': 'Herbivore - 853040006040 - Orchid (8mL) UPC (CS)',
            'Item': 'LB3433',
            'Item Category': 'Labels'},
 'UPC005': {'Description': 'Herbivore - 853040006057 - Phoenix (8mL) UPC (CS)',
            'Item': 'LB3434',
            'Item Category': 'Labels'},
 'UPC007': {'Description': 'Herbivore - 853040006071 - Pink Clay Mask UPC (CS)',
            'Item': 'LB3435',
            'Item Category': 'Labels'},
 'UPC015': {'Description': 'Herbivore - 853040006149 - Jasmine Body Oil (2oz) '
                           'UPC (CS)',
            'Item': 'LB3436',
            'Item Category': 'Labels'},
 'UPC016': {'Description': 'Herbivore - 853040006156 - Citrine Body Oil (2oz) '
                           'UPC (CS)',
            'Item': 'LB3437',
            'Item Category': 'Labels'},
 'UPC017-T': {'Description': 'Herbivore - 853040006460 - Sea Mist Texturizing '
                             'Salt Spray (2oz) - Lavender UPC (CS)',
              'Item': 'LB5187',
              'Item Category': 'Labels'},
 'UPC018-T': {'Description': 'Herbivore - 853040006477 - Sea Mist Texturizing '
                             'Salt Spray (2oz) - Coconut UPC (CS)',
              'Item': 'LB5188',
              'Item Category': 'Labels'},
 'UPC034': {'Description': 'Herbivore - 853040006293 - Beard Tonic (1oz) - '
                           'Vetiver + Sage UPC (CS)',
            'Item': 'LB3438',
            'Item Category': 'Labels'},
 'UPC035': {'Description': 'Herbivore - 853040006309 - Beard Tonic (1oz) - '
                           'Cedar + Bergamot UPC (CS)',
            'Item': 'LB5182',
            'Item Category': 'Labels'},
 'UPC036': {'Description': 'Herbivore - 853040006323 - Beard Tonic Sampler UPC '
                           '(CS)',
            'Item': 'LB5184',
            'Item Category': 'Labels'},
 'UPC038': {'Description': 'Herbivore - 853040006347 - Post Shave Elixir (4oz) '
                           'UPC (CS)',
            'Item': 'LB5102',
            'Item Category': 'Labels'},
 'UPC039': {'Description': 'Herbivore - 853040006163 - After Sun (8oz) UPC '
                           '(CS)',
            'Item': 'LB3235',
            'Item Category': 'Labels'},
 'UPC039-T': {'Description': 'Herbivore - 853040006453 - After Sun Soothing '
                             'Aloe Mist (2oz) UPC (CS)',
              'Item': 'LB5151',
              'Item Category': 'Labels'},
 'UPC041': {'Description': 'Herbivore - 853040006316 - Beard Tonic (1oz) - '
                           'Palo Santo UPC (CS)',
            'Item': 'LB5183',
            'Item Category': 'Labels'},
 'UPC052-T': {'Description': 'Herbivore - 853040006767 - Jasmine Green Tea '
                             'Toner (2oz) UPC (CS)',
              'Item': 'LB3236',
              'Item Category': 'Labels'},
 'UPC079-5M': {'Description': 'Herbivore - 850009804600 - Emerald CBD (5mL) '
                              'UPC (CS)',
               'Item': 'LB3229',
               'Item Category': 'Labels'},
 'UPC079-D': {'Description': 'Herbivore - 850001195591 - Emerald CBD (10mL) '
                             'UPC (CS)',
              'Item': 'LB3356',
              'Item Category': 'Labels'},
 'UPC080-5M': {'Description': 'Herbivore - 850009804594 - Emerald OG (5mL) UPC '
                              '(CS)',
               'Item': 'LB3228',
               'Item Category': 'Labels'},
 'UPC080-D': {'Description': 'Herbivore - 850001195522 - Emerald OG (10mL) UPC '
                             '(CS)',
              'Item': 'LB350031',
              'Item Category': 'Labels'},
 'UPC082-5M': {'Description': 'Herbivore - 850009804587 - Bakuchiol (5mL) UPC '
                              '(CS)',
               'Item': 'LB3364',
               'Item Category': 'Labels'},
 'UPC082-D': {'Description': 'Herbivore - 850001195621 - Bakuchiol (10mL) UPC '
                             '(CS)',
              'Item': 'LB3357',
              'Item Category': 'Labels'},
 'UPC090': {'Description': 'Herbivore - 850009804198 - Rose Mist [2.0] (4oz) '
                           'UPC (CS)',
            'Item': 'LB3358',
            'Item Category': 'Labels'},
 'UPC091-5M': {'Description': 'Herbivore - 850009804563 - Prism 12% Serum '
                              '(5mL) UPC (CS)',
               'Item': 'LB3362',
               'Item Category': 'Labels'},
 'UPC091-D': {'Description': 'Herbivore - 10 mL Prism 12% Serum Deluxe Sample '
                             'UPC Label (CS)',
              'Item': 'LB3350',
              'Item Category': 'Labels'},
 'UPC091-K': {'Description': 'Herbivore - 850009804969 - Prism 12% Serum '
                             '(15mL) UPC (CS)',
              'Item': 'LB3366',
              'Item Category': 'Labels'},
 'UPC092-5M': {'Description': 'Herbivore - 850009804570 - Prism 20% Mask (5mL) '
                              'UPC (CS)',
               'Item': 'LB3363',
               'Item Category': 'Labels'},
 'UPC092-K': {'Description': 'Herbivore - 850009804457 - Prism 20% Mask (15mL) '
                             'UPC (CS)',
              'Item': 'LB3426',
              'Item Category': 'Labels'},
 'UPC092-M': {'Description': 'Herbivore - 7.5 mL Prism 20% UPC Label (CS)',
              'Item': 'LB350029',
              'Item Category': 'Labels'},
 'UPC102-D': {'Description': 'Herbivore - 850009804754 - Pink Cloud Cleanser '
                             '(15mL) UPC (CS)',
              'Item': 'LB3230',
              'Item Category': 'Labels'},
 'UPC116-M': {'Description': 'Herbivore - 850009804914 - Aquarius Cream '
                             '(7.5mL) UPC (CS)',
              'Item': 'LB3428',
              'Item Category': 'Labels'},
 'UPC119-D': {'Description': 'Herbivore - 850026905106 - Cloud Jelly Serum '
                             '(5mL) UPC (CS)',
              'Item': 'LB3429',
              'Item Category': 'Labels'},
 'UPC120': {'Description': 'Herbivore - 850009804952 - Bakuchiol (30mL) UPC '
                           '(CS)',
            'Item': 'LB350032',
            'Item Category': 'Labels'},
 'UPCGEMCC1': {'Description': 'Herbivore - 850009804471 - Citrine Crystal '
                              'Cluster UPC (CS)',
               'Item': 'LB3360',
               'Item Category': 'Labels'},
 'UPCGEMCQ1': {'Description': 'Herbivore - 850009804976 - Clear Quartz Cluster '
                              'UPC (CS)',
               'Item': 'LB3234',
               'Item Category': 'Labels'},
 'UPCGS1': {'Description': 'Herbivore - 850001195041 - Rose Quartz Gua Sha '
                           'Square UPC (CS)',
            'Item': 'LB5101',
            'Item Category': 'Labels'},
 'UPCGS2': {'Description': 'Herbivore - 850001195034 - Rose Quartz Gua Sha '
                           'Teardrop UPC (CS)',
            'Item': 'LB350030',
            'Item Category': 'Labels'},
 'UPCGS4': {'Description': 'Herbivore - 850001195258 - Rose Quartz Gua Sha '
                           'Heart UPC (CS)',
            'Item': 'LB5180',
            'Item Category': 'Labels'},
 'UPCGS5': {'Description': 'Herbivore - 850009804228 - Amethyst Gua Sha UPC '
                           '(CS)',
            'Item': 'LB3425',
            'Item Category': 'Labels'},
 'UPCGS6': {'Description': 'Herbivore - 850009804532 - Jade Gua Sha Heart UPC '
                           '(CS)',
            'Item': 'LB3427',
            'Item Category': 'Labels'},
 'UPCGS7': {'Description': 'Herbivore - 850026905298 - Lapis Gua Sha Teardrop '
                           'UPC (CS)',
            'Item': 'LB5181',
            'Item Category': 'Labels'},
 'UPCGWP01': {'Description': 'Herbivore - 850026905120 - 2021 GWP Bundle 01 '
                             'UPC [8mL Lapis, 5mL Bakuchiol, 7.5mL Prism 20%] '
                             '(CS)',
              'Item': 'LB3430',
              'Item Category': 'Labels'},
 'UPCGWP02': {'Description': 'Herbivore - 850026905151 - 2021 GWP Bundle 02 '
                             'UPC [Lapis Packette, 5mL Bakuchiol, 8mL Phoenix] '
                             '(CS)',
              'Item': 'LB3431',
              'Item Category': 'Labels'},
 'UPCSE001': {'Description': 'Herbivore - 850009804853 - Sephora VIB Kit UPC '
                             '(CS)',
              'Item': 'LB3231',
              'Item Category': 'Labels'},
 'UPCUO-1': {'Description': 'Herbivore - 853040006507 - Hair Perfume (2oz) - '
                            'Rose UPC (CS)',
             'Item': 'LB5189',
             'Item Category': 'Labels'},
 'UPCUO-2': {'Description': 'Herbivore - 853040006514 - Hair Perfume (2oz) '
                            'Apricot UPC (CS)',
             'Item': 'LB5190',
             'Item Category': 'Labels'},
 'UPCUO-3': {'Description': 'Herbivore - 853040006521 - Hair Perfume (2oz) '
                            'Jasmine UPC (CS)',
             'Item': 'LB5191',
             'Item Category': 'Labels'}}

def f(x):
    for k, v in sku_map[x].items():
        print('{0} = {1}'.format(k, v))
    pyperclip.copy(sku_map[x]['Item'])
